- include: preflight.yml

- include: orchard-{{ orchard_action }}.yml
  static: no
  when: orchard_action in ["install", "upgrade"]

- name: ensure IIS is started and configured to auto-start
  win_service:
    name: w3svc
    state: started
    start_mode: auto

- name: Configure IIS AppPool
  win_iis_webapppool:
    name: '{{ orchard_cms_apppool_name }}'
    state: started

- name: Configure IIS application
  win_iis_webapplication:
    site: Default Web Site    
    name: Orchard
    application_pool: '{{ orchard_cms_apppool_name }}'
    physical_path: '{{ orchard_install_path }}'

# - name: ensure orchard SQL Server database exists
#   win_mssql_database: 
#     db_name: '{{ orchard_db_name }}'
#     state: present

# - name: ensure SQL Server login exists for AppPool identity 
#   win_mssql_server_login:
#     name: 'IIS APPPOOL\{{ orchard_cms_apppool_name }}'
#     login_type: windows
#     state: present

# - name: ensure orchard database user/roles exist
#   win_mssql_db_user:
#     db_name: '{{ orchard_db_name }}'
#     name: '{{ orchard_cms_apppool_name }}'
#     server_login_name: 'IIS APPPOOL\{{ orchard_cms_apppool_name }}'
#     roles: db_owner
#     state: present

# - name: query orchard setup state
#   raw: '{{ orchard_install_path }}\bin\orchard.exe help setup'
#   changed_when: false
#   register: orchsetup_out

# - name: run orchard site setup
#   raw: '{{ orchard_install_path }}\bin\orchard.exe setup "/SiteName:{{ orchard_site_name }}" "/AdminUsername:{{ orchard_admin_user }}" "/AdminPassword:{{ orchard_admin_password }}" /DatabaseProvider:SQLServer "/DatabaseConnectionString:{{ orchard_db_connection_string }}" /Recipe:Default'
#   when: orchsetup_out.stdout is not search("Command setup doesn't exist")

# TODO: fetch orchard site setup result
